# Generated by Django 6.0 on 2025-12-17 10:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtopic',
            name='concept_explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
