# Generated by Django 6.0 on 2025-12-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_profile_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='learning.topic'),
        ),
        migrations.DeleteModel(
            name='LearningTopic',
        ),
    ]
