# Generated by Django 6.0 on 2025-12-23 10:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_topic_difficulty_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
