# Generated by Django 6.0 on 2025-12-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
