# Generated by Django 6.0 on 2025-12-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_topic_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='rejection_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Changes Required')], default='draft', max_length=20),
        ),
    ]
