# Generated by Django 6.0 on 2025-12-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_topic_rejection_notes_alter_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Changes Required')], default='draft', max_length=20),
        ),
    ]
